export enum EntityPrefix {
  CLIENT = "CL",
  AFFILIATE = "AF",
  CAMPAIGN = "CM",
  LEAD = "LD",
  CREDENTIAL = "CR",
  CREDENTIAL_SCHEMA = "CS",
  PLUGIN_SETTING = "PG",
  CRITERIA_FIELD = "CF",
  LOGIC_RULE = "LR",
  LOGIC_RULE_GROUP = "LG",
  LOGIC_RULE_CONDITION = "LC",
}
