import { beforeEach, describe, expect, it, vi } from "vitest";
import { CherryPickService } from "../../services/cherry-pick.service";
import { CampaignParticipantStatus } from "../../../campaigns/enums/campaign-participant-status.enum";

/**
 * Cherry-pick metrics fanout contract:
 *   - On success, `MetricsService.recordLeadCherryPick` is invoked exactly once
 *     with the persisted lead and the same `executed_at` timestamp written to
 *     `cherry_pick_meta` (so day/hour buckets line up with the audit record).
 *   - A second `executeCherryPick` for the same lead is a no-op (the early
 *     `lead.cherry_picked` guard returns before any metrics emission), which
 *     gives us idempotency at the service boundary on top of the
 *     `cherry_pick:<lead_id>` sentinel enforced inside MetricsService.
 *   - When the metrics emit throws, the cherry-pick still succeeds (the lead
 *     row is already persisted) and the failure is forwarded to the shared
 *     metrics DLQ via `MetricsDlqClient.enqueue`.
 */
describe("CherryPickService cherry-pick metric emission", () => {
  let dynamoDBUtil: any;
  let logger: any;
  let lambdaInvokeUtil: any;
  let constants: any;
  let auditWriterService: any;
  let metricsService: any;
  let metricsDlqClient: any;
  let service: CherryPickService;

  const baseLead = {
    id: "LD-CP-1",
    campaign_id: "CM1",
    campaign_key: "K1",
    affiliate_id: "AF1",
    created_at: "2026-05-01T12:00:00.000Z",
    cherry_picked: false,
    cherry_pickable: true,
    sold: false,
    rejected: false,
  };

  const baseCampaign = {
    id: "CM1",
    clients: [
      {
        client_id: "CLT1",
        status: CampaignParticipantStatus.LIVE,
        delivery_config: {
          url: "https://example.test/cherry",
          method: "POST",
          claim_trusted_form: false,
        },
      },
    ],
  };

  const acceptedDelivery = {
    accepted: true,
    status_code: 200,
    response_body: "{}",
    delivered_at: "2026-05-10T09:30:00.000Z",
  };

  beforeEach(() => {
    dynamoDBUtil = {
      get: vi.fn(),
      update: vi.fn().mockResolvedValue(undefined),
    };
    logger = {
      error: vi.fn(),
      info: vi.fn(),
      warn: vi.fn(),
      debug: vi.fn(),
    };
    lambdaInvokeUtil = { invoke: vi.fn() };
    constants = {
      LEADS_TABLE_NAME: "leads",
      CAMPAIGNS_TABLE_NAME: "campaigns",
      CLIENTS_TABLE_NAME: "clients",
    };
    auditWriterService = {
      writeAuditEvent: vi.fn().mockResolvedValue(undefined),
    };
    metricsService = {
      recordLeadCherryPick: vi.fn().mockResolvedValue(undefined),
    };
    metricsDlqClient = {
      enqueue: vi.fn().mockResolvedValue(true),
    };

    service = new CherryPickService(
      dynamoDBUtil,
      logger,
      lambdaInvokeUtil,
      constants,
      auditWriterService,
      metricsService,
      metricsDlqClient,
    );

    // `executeWebhook` does real HTTP I/O; stub it on the instance so the
    // happy path can drive the cherry-pick state machine without a network.
    vi.spyOn(service as any, "executeWebhook").mockResolvedValue(
      acceptedDelivery,
    );
  });

  it("invokes recordLeadCherryPick once on the success path with the cherry-pick executed_at", async () => {
    dynamoDBUtil.get
      .mockResolvedValueOnce({ ...baseLead })
      .mockResolvedValueOnce({ ...baseCampaign });

    const result = await service.executeCherryPick("LD-CP-1", {
      target_client_id: "CLT1",
    } as never);

    expect(result.result).toBe(true);
    expect(metricsService.recordLeadCherryPick).toHaveBeenCalledTimes(1);

    const [leadArg, executedAtArg] =
      metricsService.recordLeadCherryPick.mock.calls[0];
    expect(leadArg.id).toBe("LD-CP-1");
    // executedAt is a fresh ISO timestamp generated by the service; assert
    // shape (not exact value) and parity with the audit `changed_at`.
    expect(typeof executedAtArg).toBe("string");
    expect(executedAtArg).toMatch(/^\d{4}-\d{2}-\d{2}T/);
    const auditCall = auditWriterService.writeAuditEvent.mock.calls[0][0];
    expect(auditCall.changed_at).toBe(executedAtArg);

    expect(metricsDlqClient.enqueue).not.toHaveBeenCalled();
  });

  it("does not emit a second metric when the same lead is cherry-picked twice (early-return idempotency)", async () => {
    // First call: lead is pickable, succeeds, emits one metric.
    dynamoDBUtil.get
      .mockResolvedValueOnce({ ...baseLead })
      .mockResolvedValueOnce({ ...baseCampaign });
    await service.executeCherryPick("LD-CP-1", {
      target_client_id: "CLT1",
    } as never);
    expect(metricsService.recordLeadCherryPick).toHaveBeenCalledTimes(1);

    // Second call: lead row now has cherry_picked = true; the service must
    // short-circuit before touching MetricsService.
    dynamoDBUtil.get.mockResolvedValueOnce({
      ...baseLead,
      cherry_picked: true,
    });

    const second = await service.executeCherryPick("LD-CP-1", {
      target_client_id: "CLT1",
    } as never);

    expect(second.result).toBe(false);
    expect(second.error).toMatch(/already been cherry-picked/);
    // No additional metric emission on the duplicate attempt.
    expect(metricsService.recordLeadCherryPick).toHaveBeenCalledTimes(1);
    expect(metricsDlqClient.enqueue).not.toHaveBeenCalled();
  });

  it("forwards a metrics emit failure to the shared metrics DLQ without rolling back the cherry-pick", async () => {
    dynamoDBUtil.get
      .mockResolvedValueOnce({ ...baseLead })
      .mockResolvedValueOnce({ ...baseCampaign });
    const emitError = new Error("dynamodb transact failed");
    metricsService.recordLeadCherryPick.mockRejectedValueOnce(emitError);

    const result = await service.executeCherryPick("LD-CP-1", {
      target_client_id: "CLT1",
    } as never);

    // Cherry-pick itself still succeeds — the lead row was already persisted
    // before the metrics emit was attempted.
    expect(result.result).toBe(true);
    expect(dynamoDBUtil.update).toHaveBeenCalledTimes(1);

    expect(metricsDlqClient.enqueue).toHaveBeenCalledTimes(1);
    const [eventArg, errorArg] = metricsDlqClient.enqueue.mock.calls[0];
    expect(eventArg).toMatchObject({
      lead_id: "LD-CP-1",
      campaign_id: "CM1",
      campaign_key: "K1",
      affiliate_id: "AF1",
      cherry_picked: 1,
      received: 0,
      accepted: 0,
      sold: 0,
      accepted_not_sold: 0,
      rejected: 0,
    });
    expect(errorArg).toBe(emitError);
  });
});
